# Generated by Django 4.0.8 on 2022-12-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='scheduling.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products+', to='scheduling.product'),
        ),
    ]
