# Generated by Django 4.1.5 on 2023-02-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (10, 'Employee'), (20, 'Accountant'), (30, 'Manager'), (40, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (10, 'Employee'), (20, 'Accountant'), (30, 'Manager'), (40, 'Admin')], default=10),
        ),
    ]
