# Generated by Django 4.1.5 on 2023-02-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeworkinghour',
            unique_together={('employee', 'date')},
        ),
    ]
