# Generated by Django 4.0.8 on 2023-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='tubs',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduling', 'Rescheduling')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
