# Generated by Django 4.1.7 on 2023-03-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchworkinghour',
            unique_together={('branch', 'week_day')},
        ),
        migrations.RemoveField(
            model_name='branchworkinghour',
            name='date',
        ),
    ]
