# Generated by Django 4.0.8 on 2022-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
