# Generated by Django 4.1.5 on 2023-02-04 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_employeeworkinghour_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchworkinghour',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
