# Generated by Django 4.1.5 on 2023-01-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_check_in_appointment_checkout_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_customer_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_dog_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
