# Generated by Django 4.0.8 on 2022-12-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_status_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Full Grooming', 'Full Grooming'), ('We Wash', 'We Wash')], default='We Wash', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, default=[], related_name='appointments', to='scheduling.service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Full Grooming', 'Full Grooming'), ('We Wash', 'We Wash')], default='We Wash', max_length=16),
        ),
    ]
