# Generated by Django 4.1.7 on 2023-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_product_sub_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='dog',
            unique_together={('owner', 'name')},
        ),
    ]
