# Generated by Django 4.1.5 on 2023-01-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_appointment_customer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='coat_type',
            field=models.CharField(choices=[('SmoothShort', 'Smooth (Short)'), ('SmoothLong', 'Smooth (Long)'), ('DoubleCoated', 'Double Coated'), ('Doodles', 'Doodles')], default='SmoothLong', max_length=20),
        ),
    ]
