# Generated by Django 4.1.5 on 2023-02-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_branchworkinghour_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchworkinghour',
            old_name='weekday',
            new_name='week_day',
        ),
        migrations.RenameField(
            model_name='branchworkinghour',
            old_name='workingHours',
            new_name='working_hours',
        ),
        migrations.AlterUniqueTogether(
            name='branchworkinghour',
            unique_together={('branch', 'date')},
        ),
    ]
