# Generated by Django 4.1.5 on 2023-01-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_last_customer_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='last_customer_appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_dog_appointment',
        ),
    ]
