# Generated by Django 4.0.8 on 2022-12-20 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='products',
            field=models.ManyToManyField(blank=True, default=[], related_name='products+', to='scheduling.product'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
