# Generated by Django 4.1.7 on 2023-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_customer_role_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='validated',
            field=models.BooleanField(default=True),
        ),
    ]
