# Generated by Django 4.1.5 on 2023-02-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_rename_weekday_branchworkinghour_week_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeworkinghour',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='employeeworkinghour',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkinghour',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
