# Generated by Django 4.1.5 on 2023-01-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_dog_coat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='checkout_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='special_handling',
        ),
    ]
