# Generated by Django 4.0.8 on 2022-12-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
