# Generated by Django 4.0.8 on 2023-01-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='tubs',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
