# Generated by Django 4.1.7 on 2023-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_dog_age_alter_dog_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
