# Generated by Django 4.1.5 on 2023-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_delete_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='customer_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dog',
            name='employee_notes',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dog',
            name='rabies_vaccination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='special_handling',
            field=models.BooleanField(default=False),
        ),
    ]
