# Generated by Django 4.1.7 on 2023-03-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='coat_type',
            field=models.CharField(choices=[('SmoothShort', 'Smooth Short'), ('SmoothLong', 'Smooth Long'), ('DoubleCoated', 'Double Coated'), ('Doodles', 'Doodles')], default='SmoothLong', max_length=20),
        ),
    ]
