# Generated by Django 4.1.7 on 2023-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_alter_dog_coat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='coat_type',
            field=models.CharField(choices=[('Smooth - Short', 'Smooth Short'), ('Smooth - Long', 'Smooth Long'), ('Double - Coated', 'Double Coated'), ('Doodles', 'Doodles')], default='Smooth - Long', max_length=20),
        ),
    ]
