# Generated by Django 4.1.7 on 2023-03-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_alter_dog_coat_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeworkinghour',
            unique_together={('employee', 'week_day')},
        ),
    ]
