version: "3.1"
services:
    web:
      restart: always
      build:
        context: .
        dockerfile: server.Dockerfile
      volumes:
        - .db_data/db.sqlite3:/db.sqlite3
      ports:
        - "80:80"
      environment:
        - PORT=80