version: "3.1"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./common
    command: >
      sh -c "python manage.py migrate && python /common/mock.py && python manage.py runserver 0.0.0.0:80"
