FROM python:3.8
WORKDIR /app

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./ ./

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate
ENV DJANGO_DEBUG=False
RUN python3 manage.py collectstatic --noinput
ENV PORT=8000
# Start the app on 0.0.0.0 port
CMD [ "python", "./manage.py", "runserver", "0.0.0.0:8000", "--settings=scrubbers_backend.settings" ]
