AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quicker API

Globals:
  Function:
    Timeout: 10

Resources:
  LambdaDockerImage:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 10
      PackageType: Image
      ImageUri: !Ref LambdaImageUri
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Parameters:
  LambdaImageUri:
    Type: String
    Description: URI of the Docker image to use for the Lambda function
    Default: lambda-docker-image
