AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quicker API

Parameters:
  LambdaImageUri:
    Type: String
    Description: The URI of the Lambda Docker image
    Default: lambda-docker-image

Globals:
  Function:
    Timeout: 10

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaDockerImage:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 10
      PackageType: Image
      ImageUri: !Ref LambdaImageUri
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

