AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Run Lambda Docker Image Locally

Globals:
  Function:
    Timeout: 5

Resources:
  LambdaDockerImage:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 10
      PackageType: Image
      ImageUri: lambda-docker-image
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword

Parameters:
  DbHost:
    Type: String
    Default: localhost
  DbPort:
    Type: String
    Default: 5432
  DbName:
    Type: String
    Default: postgres
  DbUser:
    Type: String
    Default: postgres
  DbPassword:
    Type: String
    Default: postgres


