# Generated by Django 4.1.7 on 2023-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_rename_token_creditcard_card_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditcard",
            options={
                "verbose_name": "Credit Card",
                "verbose_name_plural": "Credit Cards",
            },
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["owner_id"], name="credit_card_owner_i_dea68d_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="creditcard",
            table="credit_card",
        ),
    ]
