name: Test, Build and Push Docker Image

on:
  push:
    branches:
      - master # or the branch you want to trigger the workflow
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt 
        pip3 install pytest

    - name: Run tests
      run: pytest # Replace with your testing command if different

  build-and-push:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . 
        push: true
        tags: | 
          ${{ steps.login-ecr.outputs.registry }}/quicker-api:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/quicker-api:latest




