name: Test, Build and Push Docker Image

on:
  push:
    branches:
      - master # or the branch you want to trigger the workflow
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt 
        pip3 install coverage
        
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_USE_SQLITE: true
    - name: Run tests & coverage
      run: |
        coverage run --source='.' --omit='*/tests/*' --omit='*/tests/*'  manage.py test
        coverage report


  build-and-push:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    - name: Build and push Docker image
      run: |
        BUILD_ARGS=$(cat .env | awk -F= '{printf("--build-arg %s=%s ", $1, $2)}')
        docker build $BUILD_ARG -t lambda-docker-image -t ${{ steps.login-ecr.outputs.registry }}/quicker-api:${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/quicker-api:latest .
        docker push ${{ steps.login-ecr.outputs.registry }}/quicker-api:latest
    - name: Check if CloudFormation stack exists
      id: check-stack
      run: |
        aws cloudformation describe-stacks --stack-name quicker-api >/dev/null 2>&1
        if [ $? -eq 0 ]; then
          echo "::set-output name=stack_exists::true"
        else
          echo "::set-output name=stack_exists::false"
        fi

    - name: Update Lambda function code
      if: steps.check-stack.outputs.stack_exists == 'true'
      run: |
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $LAMBDA_IMAGE_URI
      env:
        LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        LAMBDA_IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/quicker-api:latest

    - name: Deploy SAM application
      if: steps.check-stack.outputs.stack_exists == 'false'
      run: |
        sam deploy --template-file packaged.yaml --stack-name quicker-api --capabilities CAPABILITY_IAM --parameter-overrides LambdaImageUri=$LAMBDA_IMAGE_URI --image-repository $LAMBDA_IMAGE_URI
      env:
        LAMBDA_IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/quicker-api:latest
